### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by pvj** [stb-tester/stb-tester#431]
Hey,

I'm wondering if there's a reason for this but upon building stbt from source on a CentOS I also had to install various libraries from pip as there seems to be no requirements.txt to work w/

If I open a PR with a req.txt would that be accepted? Thanks! Bests, 

pv

**Comment by drothlis** [comment]
Hi @pvj 

We don't install dependencies from pip because we have a lot of dependencies that aren't pure Python (or don't have any Python at all). To make packaging for Linux distros easier we have a loose policy of only allowing dependencies that have packages in debian/ubuntu.

You can see the list of build- and run-time dependencies for our ubuntu packages in [extra/debian/control]. I suppose you'll be more interested in our Fedora packaging scripts in [extra/fedora/stb-tester.spec.in] but the dependencies there may be slightly out of date because we've stopped maintaining the Fedora packages since [v26] a year ago (our download statistics indicated that no-one was using them, and no-one has volunteered to maintain them).

Does it meet your needs to install the dependencies using the CentOS package manager? Or do you have a use case where it would still be useful to have a requirements.txt file?

[extra/debian/control]: https://github.com/stb-tester/stb-tester/blob/master/extra/debian/control
[extra/fedora/stb-tester.spec.in]: https://github.com/stb-tester/stb-tester/blob/master/extra/fedora/stb-tester.spec.in
[v26]: https://github.com/stb-tester/stb-tester/blob/master/docs/release-notes.md#26
